language: python
os: linux

script:
  - py.test --cov=website tests/
  - flake8 .

install: pipenv install --dev

jobs:
  include:
    - stage: 'test'
      python: 3.7
      after_success: coveralls
    - stage: 'test'
      python: 3.6
    - stage: 'semantic versioning'
      if: branch = master AND type != pull_request
      python: 3.7
      install: skip
      script: echo "Publishing a new release"
      after_success:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - pip install python-semantic-release
        - semantic-release publish

