language: python
python:
  - '3.6'

install:
  - 'pip install pytest-cov'
  - 'pip install coveralls'
  - 'pip install pipenv'
  - 'pipenv install'

script:
  - py.test --cov=website tests/

after_success:
  - coveralls
