name: PR Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7']
    name: python ${{ matrix.python-version }} CI

    steps:
    - name: Checkout code
      uses: actions/checkout@v1.2.0

    - name: Set up python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Generate requirements.txt
      run: pipenv lock -r > requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        BASE_URL: http://base_url/
        FLASK_APP: website
        FLASK_ENV: development
      run: |
        pip install pytest pytest-cov responses
        pytest --cov-report= --cov=website tests/

    - name: Code coverage analysis
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./coverage

    - name: Coveralls finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
